services:
  polaris-init:
    image: curlimages/curl:8.5.0
    depends_on:
      polaris:
        condition: service_healthy
    networks:
      - local-iceberg-lakehouse
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "/scripts/init.sh"]

  polaris:
    image: apache/polaris:latest
    platform: linux/amd64
    ports:
      - "8181:8181"
      - "8182:8182"
    networks:
      - local-iceberg-lakehouse
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: dummy-region
      AWS_ENDPOINT_URL_S3: http://minio:9000
      AWS_ENDPOINT_URL_STS: http://minio:9000
      POLARIS_BOOTSTRAP_CREDENTIALS: default-realm,root,secret
      polaris.features.DROP_WITH_PURGE_ENABLED: true
      polaris.realm-context.realms: default-realm
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/q/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  postgres-db:
    image: postgres:15.4
    ports:
      - "15435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - local-iceberg-lakehouse
    volumes:
      - postgres-db-volume-db:/var/lib/postgresql/data

  # for testing purposes, we can use a single Trino container with both coordinator and worker roles, but for better performance and scalability, it's recommended to separate them into different containers.
  # trino:
  #   image: trinodb/trino:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - TRINO_JVM_OPTS=-Xmx2G
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   networks:
  #     - local-iceberg-lakehouse
  #   volumes:
  #     - ./trino/catalog:/etc/trino/catalog
  #   depends_on:
  #     - minio

  trino-coordinator:
    image: trinodb/trino:latest
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./trino/coordinator:/etc/trino
      - ./trino-spill:/tmp/trino-spill
      - ./trino-exchange:/tmp/trino-exchange
    networks:
      - local-iceberg-lakehouse
    depends_on:
      - minio

  trino-worker-1:
    image: trinodb/trino:latest
    container_name: trino-worker-1
    volumes:
      - ./trino/worker1:/etc/trino
      - ./spill-worker1:/tmp/trino-spill
      - ./trino-exchange:/tmp/trino-exchange

    networks:
      - local-iceberg-lakehouse
    depends_on:
      - trino-coordinator

  trino-worker-2:
    image: trinodb/trino:latest
    container_name: trino-worker-2
    volumes:
      - ./trino/worker2:/etc/trino
      - ./spill-worker2:/tmp/trino-spill
      - ./trino-exchange:/tmp/trino-exchange

    networks:
      - local-iceberg-lakehouse
    depends_on:
      - trino-coordinator

  trino-worker-3:
    image: trinodb/trino:latest
    container_name: trino-worker-3
    volumes:
      - ./trino/worker3:/etc/trino
      - ./spill-worker3:/tmp/trino-spill
      - ./trino-exchange:/tmp/trino-exchange

    networks:
      - local-iceberg-lakehouse
    depends_on:
      - trino-coordinator


  minio:
    image: minio/minio:latest
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: dummy-region
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    networks:
      local-iceberg-lakehouse:
        aliases:
          - warehouse.minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - local-iceberg-lakehouse
    volumes:
      - /tmp:/tmp
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: dummy-region
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      mc rm -r --force minio/warehouse;
      mc mb minio/warehouse;
      mc anonymous set public minio/warehouse;
      tail -f /dev/null
      " 
networks:
  local-iceberg-lakehouse:
    name: local-iceberg-lakehouse

volumes:
  postgres-db-volume-db:
